### ISSUE TITLE
DoH not compatible with ktor 2.0

### ISSUE THREAD

**Issue by jan-tennert** [relaycorp/doh-jvm#124]
# Describe the bug
I think the title describes it very good. Ktor 2.0 changes how features (now plugins) work etc. and DoH doesn't like that currently

**Comment by gnarea** [comment]
Thanks for taking the time to report this, @jan-tennert!

Agreed, this is something we too want. We're currently planning to upgrade to Kotlin 1.6 and Ktor 2 across all of our repos over the next couple of months, but PRs are also welcomed.
